version: '3.8'
services:
  api:
    container_name: api-synapsis
    restart: always
    build: .
    ports:
      - '7979:7979'
    depends_on:
      - db
    volumes:
    - .:/usr/src/app
    networks:
      - synapsis
  db:
    container_name: db-synapsis
    image: postgres
    restart: always
    ports:
      - '7878:5432'
    volumes:
      - ./Database/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - data:/data/database
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - synapsis
volumes: 
 data: {}
#define network
networks:
  synapsis:
    driver: bridge
